=== Malhoura/ITMD466-566-XML-Parsing/SaxParser/dtd/customer.dtd
<!DOCTYPE customer
[
<!ELEMENT customers (customer+)>
<!ELEMENT customer (customerID,state,customerName,businessName, billingAddress, city, state, postalCode, country, phoneNumber, otherNumber, faxNumber, emailAddress, customerType, companyName, contactName, alternateContactName, date)>
<!ELEMENT customerID (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT customerName (#PCDATA)>
<!ELEMENT businessName (#PCDATA)>
<!ELEMENT billingAddress (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT otherNumber (#PCDATA)>
<!ELEMENT faxNumber (#PCDATA)>
<!ELEMENT emailAddress (#PCDATA)>
<!ELEMENT customerType (#PCDATA)>
<!ELEMENT companyName (#PCDATA)>
<!ELEMENT contactName (#PCDATA)>
<!ELEMENT alternateContactName (#PCDATA)>
<!ELEMENT date (#PCDATA)>
]>

=== Malhoura/ITMD466-566-XML-Parsing/SaxParser/xml/customer.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE customer SYSTEM "customer.dtd">

<customers> 

<customer id="001">
	<state>IL</state>
	<customerName>Mazen-1</customerName>
	<businessName>Business-1</businessName>
	<billingAddress>3128 south wells</billingAddress>
	<city>Chicago</city>
	<postalCode>60616</postalCode>
	<country>USA</country>
	<phoneNumber>3128885475</phoneNumber>
	<otherNumber></otherNumber>
	<faxNumber></faxNumber>
	<emailAddress>malhoura@hawk.iit.edu</emailAddress>
	<customerType>type-1</customerType>
	<companyName>IIT</companyName>
	<contactName>Zing</contactName>
	<alternateContactName></alternateContactName>
	<date>03251992</date>
</customer>

<customer id="002">
	<state>NY</state>
	<customerName>Mazen-2</customerName>
	<businessName>Business-2</businessName>
	<billingAddress>3241 south wabash</billingAddress>
	<city>Chicago</city>
	<postalCode>60161</postalCode>
	<country>USA</country>
	<phoneNumber>3123123333</phoneNumber>
	<otherNumber></otherNumber>
	<faxNumber></faxNumber>
	<emailAddress>mazen.alhoura@gmail.com</emailAddress>
	<customerType>type-2</customerType>
	<companyName>ITT</companyName>
	<contactName>Zingos</contactName>
	<alternateContactName></alternateContactName>
	<date>05151992</date>
</customer>

</customers>
