=== Malhoura/ITMD466-566-XML-Parsing/SaxParser/dtd/location.dtd
<!DOCTYPE location
[
<!ELEMENT locations (location+)>
<!ELEMENT location (locationID,locationName,locationCode,isAuction, customerID, adressStreet1, adressStreet2, city, state, postalCode, region, locationContactName, locationPhone, locationFaxNumber, locationEmail)>
<!ELEMENT locationID (#PCDATA)>
<!ELEMENT locationName (#PCDATA)>
<!ELEMENT locationCode (#PCDATA)>
<!ELEMENT isAuction (#PCDATA)>
<!ELEMENT customerID (#PCDATA)>
<!ELEMENT adressStreet1 (#PCDATA)>
<!ELEMENT adressStreet2 (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT locationContactName (#PCDATA)>
<!ELEMENT locationPhone (#PCDATA)>
<!ELEMENT locationFaxNumber (#PCDATA)>
<!ELEMENT locationEmail (#PCDATA)>
]>

=== Malhoura/ITMD466-566-XML-Parsing/SaxParser/xml/location.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE location SYSTEM "location.dtd">

<locations> 

<location id="001">
	<locationName>location-1</locationName>
	<locationCode>Chi</locationCode>
	<customerID>1</customerID>
	<adressStreet1>3128 south wells</adressStreet1>
	<adressStreet2>3R</adressStreet2>
	<city>Chicago</city>
	<state>IL</state>
	<postalCode>60616</postalCode>
	<region>Cook</region>
	<locationContactName>Zing</locationContactName>
	<locationPhone>3333333333</locationPhone>
	<locationFaxNumber></locationFaxNumber>
	<locationEmail> loc@gmail.com</locationEmail>
</location>

</locations>
