=== Malhoura/ITMD466-566-XML-Parsing/SaxParser/dtd/price.dtd
<!DOCTYPE price
[
<!ELEMENT prices (price+)>
<!ELEMENT price (priceID,locationID,locationIDFrom,locationIDTo, price, locationCodeFrom, locationCodeTo, customerID)>
<!ELEMENT priceID (#PCDATA)>
<!ELEMENT locationID (#PCDATA)>
<!ELEMENT locationIDFrom (#PCDATA)>
<!ELEMENT locationIDTo (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT locationCodeFrom (#PCDATA)>
<!ELEMENT locationCodeTo (#PCDATA)>
<!ELEMENT customerID (#PCDATA)>
]>

=== Malhoura/ITMD466-566-XML-Parsing/SaxParser/xml/price.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE price SYSTEM "price.dtd">

<prices>
    
<price>
	<priceID> </priceID>
	<locationID> </locationID>
	<locationIDFrom> </locationIDFrom>
	<locationIDTo> </locationIDTo>
	<price> </price>
	<locationCodeFrom> </locationCodeFrom>
	<locationCodeTo> </locationCodeTo>
	<customerID> </customerID>
</price>

<price>
	<priceID> </priceID>
	<locationID> </locationID>
	<locationIDFrom> </locationIDFrom>
	<locationIDTo> </locationIDTo>
	<price> </price>
	<locationCodeFrom> </locationCodeFrom>
	<locationCodeTo> </locationCodeTo>
	<customerID> </customerID>
</price>

</prices>
