=== Malhoura/ITMD466-566-XML-Parsing/SaxParser/dtd/transaction.dtd
<!DOCTYPE transaction
[
<!ELEMENT transactions (transaction+)>
<!ELEMENT transaction (transactionID,orderID,priceID,transactionDate, transactionDescription, transactionAmount, VIN, truckNo, employeeID, discount, quantity, unitPrice, driverPrice)>
<!ELEMENT transactionID (#PCDATA)>
<!ELEMENT orderID (#PCDATA)>
<!ELEMENT priceID (#PCDATA)>
<!ELEMENT transactionDate (#PCDATA)>
<!ELEMENT transactionDescription (#PCDATA)>
<!ELEMENT transactionAmount (#PCDATA)>
<!ELEMENT VIN (#PCDATA)>
<!ELEMENT truckNo (#PCDATA)>
<!ELEMENT employeeID (#PCDATA)>
<!ELEMENT discount (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unitPrice (#PCDATA)>
<!ELEMENT driverPrice (#PCDATA)>
]>

=== Malhoura/ITMD466-566-XML-Parsing/SaxParser/xml/transaction.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE transaction SYSTEM "transaction.dtd">

<transactions> 
<transaction> 
	<transactionID> </transactionID>
	<orderID> </orderID>
	<priceID> </priceID>
	<transactionDate> </transactionDate>
	<transactionDescription> </transactionDescription>
	<transactionAmount> </transactionAmount>
	<VIN> </VIN>
	<truckNo> </truckNo>
	<employeeID> </employeeID>
	<discount> </discount>
	<quantity> </quantity>
	<unitPrice> </unitPrice>
	<driverPrice> </driverPrice>
</transaction>
</transactions>
