=== Malhoura/ITMD466-566-XML-Parsing/SaxParser/dtd/truck.dtd
<!DOCTYPE truck
[
<!ELEMENT trucks (truck+)>
<!ELEMENT truck (VIN,truckNo,makeYear,model, licensePlateNo, employeeID, color, cost)>
<!ELEMENT VIN (#PCDATA)>
<!ELEMENT truckNo (#PCDATA)>
<!ELEMENT makeYear (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT licensePlateNo (#PCDATA)>
<!ELEMENT employeeID (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
]>

=== Malhoura/ITMD466-566-XML-Parsing/SaxParser/xml/truck.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE truck SYSTEM "truck.dtd">
<trucks> 
<truck> 
	<VIN> </VIN>
	<truckNo> </truckNo>
	<makeYear> </makeYear>
	<model> </model>
	<licensePlateNo> </licensePlateNo>
	<employeeID> </employeeID>
	<color> </color>
	<cost> </cost>
</truck>
</trucks>
